version: "3"
services:
  basic_server:
    image: ${DOCKER_USERNAME}/nodejs_basic_server:latest
    command: "npm run test"
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
  data_analyzer:
    image: ${DOCKER_USERNAME}/nodejs_data_analyzer_server:latest
    command: "npm run test"
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    depends_on:
      - mongo
  mongo:
    image: registry.semaphoreci.com/mongo:4.4
    command: mongod --logpath=/dev/null # --quiet
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"
  data_collector:
    image: ${DOCKER_USERNAME}/nodejs_data_collector_server:latest
    command: "npm run test"
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
    depends_on:
      - mongo
