version: "3"
services:
  basic_server:
    build: ./applications/basic_server
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
  data_analyzer:
    build: ./applications/data_analyzer_server
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    depends_on:
      - mongo
  mongo:
    image: registry.semaphoreci.com/mongo:4.4
    command: mongod --logpath=/dev/null # --quiet
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"
  data_collector:
    build: ./applications/data_collector_server
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
